//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Resources.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activitied..
        /// </summary>
        public static string Account_Activitied {
            get {
                return ResourceManager.GetString("Account_Activitied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong! Your account can&apos;t active.
        /// </summary>
        public static string Account_Activitied_Wrong {
            get {
                return ResourceManager.GetString("Account_Activitied_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name exist!!!.
        /// </summary>
        public static string Account_Exist {
            get {
                return ResourceManager.GetString("Account_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can use this account name!!!.
        /// </summary>
        public static string Account_NoExist {
            get {
                return ResourceManager.GetString("Account_NoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Your Account by Mail..
        /// </summary>
        public static string Active_Account_Alert {
            get {
                return ResourceManager.GetString("Active_Account_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender.
        /// </summary>
        public static string Choose_Gender {
            get {
                return ResourceManager.GetString("Choose_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Account Name must contain from 5 to 30 characters and dont have spacewhite..
        /// </summary>
        public static string Invalid_Account_Name {
            get {
                return ResourceManager.GetString("Invalid_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Address must contain from 10 to 200 characters..
        /// </summary>
        public static string Invalid_Address {
            get {
                return ResourceManager.GetString("Invalid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Birthday!.
        /// </summary>
        public static string Invalid_Birthday {
            get {
                return ResourceManager.GetString("Invalid_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your gender..
        /// </summary>
        public static string Invalid_Choose_Gender {
            get {
                return ResourceManager.GetString("Invalid_Choose_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Email must contain from 8 to 50 characters..
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Password must contain from 8 to 50 characters and dont have spacewhite..
        /// </summary>
        public static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Phone Number must contain from 9 to 13 characters..
        /// </summary>
        public static string Invalid_Phone_Number {
            get {
                return ResourceManager.GetString("Invalid_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill User Name must contain from 5 to 50 characters..
        /// </summary>
        public static string Invalid_User_Name {
            get {
                return ResourceManager.GetString("Invalid_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Login.
        /// </summary>
        public static string Return_Login {
            get {
                return ResourceManager.GetString("Return_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong.
        /// </summary>
        public static string Something_Wrong {
            get {
                return ResourceManager.GetString("Something_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Account_Name {
            get {
                return ResourceManager.GetString("Valid_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Address {
            get {
                return ResourceManager.GetString("Valid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Birthday {
            get {
                return ResourceManager.GetString("Valid_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Choose_Gender {
            get {
                return ResourceManager.GetString("Valid_Choose_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Email {
            get {
                return ResourceManager.GetString("Valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Password {
            get {
                return ResourceManager.GetString("Valid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_Phone_Number {
            get {
                return ResourceManager.GetString("Valid_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks good!.
        /// </summary>
        public static string Valid_User_Name {
            get {
                return ResourceManager.GetString("Valid_User_Name", resourceCulture);
            }
        }
    }
}
